server:
  use-forward-headers: true
  error:
    whitelabel:
      enabled: false

spring:
  jmx:
    enabled: false
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**
