server:
  use-forward-headers: true
spring:
  jmx:
    enabled: false
  resources:
    chain:
      cache: true
      strategy:
        content:
          enabled: true
          paths: /**

error:
  whitelabel:
    enabled: false
